name: Deploy to Azure Windows VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Upload files to Windows VM (No zip/tar, wildcard for files)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: "/*"  # Wildcard to upload all files in the repository
          target: "C:/Users/${{ secrets.AZURE_VM_USERNAME }}/Desktop"
          rm: false
          strip_components: 0

      - name: SSH into Windows VM and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            powershell -Command "
              # Navigate to the folder where files were uploaded
              cd 'C:\Users\${{ secrets.AZURE_VM_USERNAME }}\Desktop';
              npm install --production;
              pm2 restart myapp || pm2 start npm --name myapp -- start;
            "
