name: Deploy to Azure Windows VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Check if .next exists
        run: |
          if [ ! -d ".next" ]; then
            echo ".next directory not found. Build may have failed."
            exit 1
          fi

      - name: Upload build files to Windows VM (no tar)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: ".next public package.json package-lock.json"
          target: "C:/Users/${{ secrets.AZURE_VM_USERNAME }}/Desktop/myapp"
          tar_exec: ""  # ⛔ disables tar compression to prevent issues on Windows
          rm: false
          strip_components: 0

      - name: SSH into Windows VM and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            powershell -Command "
              cd 'C:\Users\${{ secrets.AZURE_VM_USERNAME }}\Desktop\myapp';
              npm install --production;
              pm2 restart myapp || pm2 start npm --name myapp -- start;
            "
